#! /bin/sh

sxhkd &

bspc config focus_follows_pointer true

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# bspc config border_width        1
# bspc config window_gap          0
# bspc config borderless_monocle	true
# bspc config gapless_monocle	    true

BW=1
bspc config border_width $BW
bspc config window_gap -$BW
for side in top right bottom left ; do
    bspc config ${side}_padding $BW
done
# Non-BSPWM related

xsetroot -cursor_name left_ptr &
amixer sset 'Master' 100% &
redshift -O 4500 &
setxkbmap -option caps:escape &
picom &

wget https://source.unsplash.com/1360x768/?nature,blue -O ~/.wallpaper.jpg
feh --bg-fill ~/.wallpaper.jpg &
