#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config focus_follows_pointer true
bspc config border_width          0
bspc config window_gap            0

bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled

# Non-BSPWM related

feh --bg-fill ~/.wallpaper.jpg &
$HOME/.config/polybar/launch.sh &
xset r rate 250 25 &
xsetroot -cursor_name left_ptr &
amixer sset 'Master' 100% &
redshift -O 4500 &
setxkbmap -option caps:escape &
picom &
wmname LG3D &
